# Generated by Django 3.0.5 on 2020-04-06 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='assets/images/')),
                ('aboutus', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description Maximum 300 words', max_length=300)),
                ('image', models.ImageField(default='', upload_to='assets/images/poster/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.SmallIntegerField()),
                ('thumbnail', models.ImageField(default='', upload_to='assets/images/product')),
                ('discount', models.SmallIntegerField(default=0, help_text='unit in percentage')),
                ('description', models.TextField(blank=True, help_text='Description Maximum 300 words', max_length=300)),
                ('date_create', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assets/images/product/')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinkland.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='categ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinkland.ProductCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='functions',
            field=models.ManyToManyField(to='pinkland.ProductFunction'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinkland.ProductMaterial'),
        ),
    ]
