# Generated by Django 3.0.3 on 2020-04-06 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description Maximum 300 words', max_length=300)),
                ('image', models.ImageField(blank=True, help_text='please upload image above 800 x 600 px', upload_to='poster_image')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('thumbnail', models.ImageField(default='/media/low-poly-texture-80.png', upload_to='product_image/')),
                ('category', models.CharField(choices=[('rose_quartz', '粉水晶'), ('amethyst', '紫水晶'), ('citrine', '黃水晶'), ('super_seven', '超級七'), ('gold_rutilated_quartz', '金髮晶'), ('green_phantom', '綠幽靈'), ('moon_stone', '月亮石'), ('labradorite', '拉長石'), ('tigers_eye', '虎眼石'), ('clear_quartz', '白水晶'), ('Aquamarine', '海藍寶'), ('pink_beryl', '摩根石'), ('rhodochrosite', '紅紋石'), ('strawberry_quartz', '草莓石'), ('white_phantom', '白幽靈'), ('sunstone', '太陽石'), ('agate', '瑪瑙')], max_length=100)),
                ('body_part', models.CharField(choices=[('bracelet', '手鏈'), ('pendant', '吊墜'), ('ring', '戒指'), ('earring', '耳環'), ('furnishing', '擺設'), ('necklace', '項鏈')], max_length=100)),
                ('func', models.CharField(blank=True, choices=[('carrer', '事業'), ('relationship', '人緣'), ('health', '健康'), ('emotion', '情緒'), ('stress_relieve', '減壓'), ('love', '愛情'), ('purification', '淨化'), ('wealth', '財運'), ('exorcise_evil', '辟邪'), ('away_from_snob', '防小人')], max_length=100)),
                ('price', models.SmallIntegerField()),
                ('discount', models.SmallIntegerField(default=0, help_text='unit in percentage')),
                ('description', models.TextField(blank=True, help_text='Description Maximum 300 words', max_length=300)),
                ('date_create', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product_image')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinkland.Product')),
            ],
        ),
    ]
