# Generated by Django 3.0.3 on 2020-02-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('p_type', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('discount', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
