# Generated by Django 3.0.3 on 2020-04-07 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinkland', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='description',
        ),
    ]
