# Generated by Django 3.0.3 on 2020-02-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinkland', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='material',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='p_type',
        ),
    ]
