# Generated by Django 3.0.3 on 2020-04-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkland', '0002_remove_poster_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='description',
            field=models.TextField(blank=True, help_text='Description Maximum 300 words', max_length=300),
        ),
    ]
