# Generated by Django 3.0.3 on 2020-02-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkland', '0002_auto_20200211_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('粉水晶', '粉水晶'), ('紫水晶', '紫水晶'), ('黃水晶', '黃水晶'), ('超級七', '超級七'), ('金髮晶', '金髮晶'), ('綠幽靈', '綠幽靈'), ('月亮石', '月亮石'), ('拉長石', '拉長石'), ('虎眼石', '虎眼石'), ('白水晶', '白水晶'), ('海藍寶', '海藍寶'), ('摩根石', '摩根石'), ('紅紋石', '紅紋石'), ('草莓石', '草莓石'), ('白幽靈', '白幽靈'), ('太陽石', '太陽石'), ('瑪瑙)', '瑪瑙')], max_length=20),
        ),
    ]
