# Generated by Django 3.0.5 on 2020-04-20 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinkland', '0003_auto_20200420_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='description',
            field=models.TextField(blank=True, help_text='Description Maximum 300 words', max_length=300, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.ImageField(default='', upload_to='assets/images/poster/', verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='title',
            field=models.CharField(max_length=50, verbose_name='標題'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinkland.ProductCategory', verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Description Maximum 300 words', max_length=300, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.SmallIntegerField(default=0, help_text='unit in percentage', verbose_name='折扣'),
        ),
        migrations.AlterField(
            model_name='product',
            name='functions',
            field=models.ManyToManyField(to='pinkland.ProductFunction', verbose_name='功能'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_discount',
            field=models.BooleanField(default=False, verbose_name='啟用 ?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinkland.ProductMaterial', verbose_name='材料'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='產品名稱'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.SmallIntegerField(verbose_name='價錢'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='assets/images/product', verbose_name='縮圖'),
        ),
    ]
