# Generated by Django 3.0.3 on 2020-03-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkland', '0005_auto_20200219_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='/media/low-poly-texture-80.png', upload_to='../media/'),
        ),
    ]
