# Generated by Django 3.0.3 on 2020-03-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkland', '0006_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body_part',
            field=models.CharField(choices=[('bracelet', '手鏈'), ('pendant', '吊墜'), ('ring', '戒指'), ('earring', '耳環'), ('furnishing', '擺設'), ('necklace', '項鏈')], default='bracelet', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='func',
            field=models.CharField(blank=True, choices=[('carrer', '事業'), ('relationship', '人緣'), ('health', '健康'), ('emotion', '情緒'), ('stress_relieve', '減壓'), ('love', '愛情'), ('purification', '淨化'), ('wealth', '財運'), ('exorcise_evil', '辟邪'), ('away_from_snob', '防小人')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('rose_quartz', '粉水晶'), ('amethyst', '紫水晶'), ('citrine', '黃水晶'), ('super_seven', '超級七'), ('gold_rutilated_quartz', '金髮晶'), ('green_phantom', '綠幽靈'), ('moon_stone', '月亮石'), ('labradorite', '拉長石'), ('tigers_eye', '虎眼石'), ('clear_quartz', '白水晶'), ('Aquamarine', '海藍寶'), ('pink_beryl', '摩根石'), ('rhodochrosite', '紅紋石'), ('strawberry_quartz', '草莓石'), ('white_phantom', '白幽靈'), ('sunstone', '太陽石'), ('agate', '瑪瑙')], max_length=100),
        ),
    ]
