# Generated by Django 3.0.3 on 2020-03-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkland', '0009_auto_20200323_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='body_part',
            field=models.CharField(choices=[('bracelet', '手鏈'), ('pendant', '吊墜'), ('ring', '戒指'), ('earring', '耳環'), ('furnishing', '擺設'), ('necklace', '項鏈')], max_length=100),
        ),
    ]
