# Generated by Django 3.0.3 on 2020-03-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkland', '0010_auto_20200323_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.SmallIntegerField(),
        ),
    ]
