# Generated by Django 3.0.3 on 2020-04-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkland', '0014_auto_20200331_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description Maximum 300 words', max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='poster_image')),
            ],
        ),
    ]
