# Generated by Django 3.0.3 on 2020-04-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkland', '0015_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.ImageField(blank=True, help_text='please upload image above 800 x 600 px', upload_to='poster_image'),
        ),
    ]
